### PR TITLE
Update Gradle to 7.2

### PR DESCRIPTION
**Pull request by gurbuzali**
### What this PR does / why do we need it:

Update Gradle to 7.2

The project was using Gradle 5.4 which is really old,
I've updated Gradle 7.2 which is the latest stable release.
I've also updated the build scripts of the projects to remove the deprecated usages.

Enable Caching

You can avoid re-running the tasks using build-caching if the inputs of the task don't change between builds.
You can use [Gradle Enterprise](https://gradle.com/enterprise) to publish your Build Scan™ to inspect and optimize your builds.

Below are 3 Build Scan™ published to [scans.gradle.com](https://scans.gradle.com):

The first build is started with an empty build cache and produced a test failure
https://scans.gradle.com/s/nsvmkyctpfzp6

The second build simply re-runs the build to see if it is a flaky test. You can observe
which tasks are re-executed and which tasks are fetched from cache (Performance -> Build Cache)
https://scans.gradle.com/s/rscttuvlyy7ga/performance/build-cache

The third build is also a re-run, now that all the build and test artifacts are cached 
this build didn't execute tasks but fetched them all from the cache
https://scans.gradle.com/s/znaxnqcckjmmq/performance/build-cache

Fix Checkstyle Cache Miss

I've also removed the `rootDir` property usage from checkstyle task and used builtin `config_loc` property instead.
This way when the build is executed from different locations (location-1: /foo/hazelcast-jet-contrib, location-2 /bar/hazelcast-jet-contrib) the inputs of the checkstyle task will remain the same and no cache-miss will occur.

Update Hazelcast to 5.0

Fix test-failures by enabling Jet
 

#### Checklist

- [ ] Signed the Hazelcast CLA
- [ ] No checkstyle issues (`./gradlew check`)
- [ ] No tests failures (`./gradlew test`)
- [ ] Documentation which complies with README template (see `templates/README.template.md`).
- [ ] Update `List of modules` section on the root README with your module.

### CODE REVIEW

**Comment by frant-hartm** [comment]
verify

**Comment by frant-hartm** [comment]
Hi,

thanks for the PR and sorry for ignoring this so far. I haven't been watching this repo.

I tried to push a minor thing to this, but seems I am not allowed to. Is the access to maintainers enabled on this PR? Could you enable it? Or maybe just push this, it removes use of deprecated API warning in the build:

```
--- a/build.gradle
+++ b/build.gradle
@@ -6,7 +6,9 @@ buildscript {
     }
     repositories {
         mavenCentral()
-        jcenter()
+        maven {
+            url 'https://plugins.gradle.org/m2/'
+        }
     }
 }
```

Thanks.

**Comment by frant-hartm** [comment]
verify

**Comment by gurbuzali** [comment]
@frant-hartm weird I have `Allow edits by maintainers` enabled already. pushed the changes

**Review by frant-hartm — APPROVED** [review]

**Comment by mmedenjak** [comment]
@gurbuzali thank you for your contribution! Hope you're doing well over there :)

**Pull request merged**
