### PR TITLE
Fix PahoClientFaultToleranceTest

### PR DESCRIPTION
**Pull request by viliam-durina**
The test takes about 70 seconds to complete. Maybe it will be faster on linux. It keeps deleting and creating directories in the temp directory for some reason.

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `jet-contrib-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-contrib-pr-builder/384/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-contrib-pr-builder/384/jet-contrib-pr-builder-384.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</details>
</pre>

**Comment by hz-highfive** [comment]
The job `jet-contrib-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-contrib-pr-builder/386/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-contrib-pr-builder/386/jet-contrib-pr-builder-386.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</details>
</pre>

**Comment by viliam-durina** [comment]
verify

**Comment by hz-highfive** [comment]
The job `jet-contrib-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-contrib-pr-builder/387/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-contrib-pr-builder/387/jet-contrib-pr-builder-387.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</details>
</pre>

**Pull request closed without merging**
