### PR TITLE
Use Hazelcast 5.0 in contrib. modules

### PR DESCRIPTION
**Pull request by ufukyilmaz**
### What this PR does / why do we need it:

This PR partially applies the platform changes on these contrib. modules.
It replaces `JetInstance` usages with `JetService`. Also, it removes the
`hazelcast-jet-spring-boot-starter` module as this won't work with
hazelcast 5.0.

#### Checklist

- [x] Signed the Hazelcast CLA
- [x] No checkstyle issues (`./gradlew check`)
- [x] No tests failures (`./gradlew test`)
- [x] Update `List of modules` section on the root README with your module.

### CODE REVIEW

**Comment by ufukyilmaz** [comment]
I think this remaining failure is related to change made on `assertJobRunningEventually(JetInstance, Job, Long)` in light job pr: https://github.com/hazelcast/hazelcast/pull/18619. I could solve it by removing its usage but I didn't want to hide this failure. I did not research in depth, I just wrote to comment.

**Review by olukas — APPROVED** [review]
LGTM, thanks! 

Regarding failing test - I think we should probably use `@Ignore` for it or try to fix it somehow. I understand it's not optimal to hide it but if we merge it will fail in every other PR builder.

**Review by gurbuzali — APPROVED** [review]

**Comment by kpe** [comment]
@ufukyilmaz  - I see jet-spring-boot-starter has been removed, however this breaks some links in the documentation (i.e. https://jet-start.sh/docs/tutorials/spring-boot) and possibly others. Is there some replacement on the way?

**Comment by ufukyilmaz** [comment]
Hi @kpe,
Thank you for reporting this issue. In this period, we are trying to combine two different products of Hazelcast, `IMDG` and `Jet`, into one merged product (you can check https://github.com/hazelcast/hazelcast repo for these changes) and I was also updating this contrib repo so that it could work with this new merged product. But I didn't think that this issue you mentioned would occur while I was doing this, sorry for the inconvenience. Now, I created jet-4.5 maintenance branch, https://github.com/hazelcast/hazelcast-jet-contrib/tree/jet-4.5-maintenance/, to be able to work with Jet 4.5 and will update that jet documentation as soon as possible.

**Pull request merged**
